# Generated by Django 5.1 on 2024-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_ads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Dress', 'Одежда'), ('Car', 'Машины'), ('Home appliances', 'Бытовая техника'), ('Phone', 'Телефон')], max_length=100, verbose_name='Категории'),
        ),
    ]
