# Generated by Django 5.1 on 2024-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='published_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
