# Generated by Django 5.1 on 2024-08-31 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_ads_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='webapp.profile', verbose_name='Автор'),
        ),
    ]
